onlineportal/core/urls.py
from django.urls import path
from . import views


app_name = 'core'
urlpatterns=[
    path('about/', views.about, name='about'),

]

onlineportal/onlineportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from classroom.views import  students, teachers, classroom,profile

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('', include('contact.urls', namespace='contact')),
    url(r'^', include('classroom.urls')),
    url(r'^', include('registrar.urls')),
    url(r'^', include('students.urls')),
    url(r'^', include('teachers.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/signup/$', classroom.SignUpView.as_view(), name='signup'),
    url(r'^accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    url(r'^accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
    path('profile/', profile.profile, name= 'profile'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

onlineportal/teachers/urls.py
from django.conf.urls import include, url


# Import custom views.
from teachers.views import announcement
from teachers.views import syllabus
from teachers.views import policy
from teachers.views import lecture
from teachers.views import lecture_note
from teachers.views import assignment
from teachers.views import quiz
from teachers.views import exam
from teachers.views import overview
from teachers.views import discussion
from teachers.views import peer_review
from teachers.views import setting

urlpatterns = [
    # Syllabus
    url(r'^teacher/course/(\d+)/overview$', overview.overview_page),
    url(r'^teacher/course/(\d+)/submit_course_for_review$', overview.submit_course_for_review),

    # Announcement
    url(r'^teacher/course/(\d+)/$', announcement.announcements_page),
    url(r'^teacher/course/(\d+)/home$', announcement.announcements_page),
    url(r'^teacher/course/(\d+)/announcement$', announcement.announcements_page),
    url(r'^teacher/course/(\d+)/announcements_table$', announcement.announcements_table),
    url(r'^teacher/course/(\d+)/announcement_modal$', announcement.announcement_modal),
    url(r'^teacher/course/(\d+)/save_announcement$', announcement.save_announcement),
    url(r'^teacher/course/(\d+)/delete_announcement$', announcement.delete_announcement),

    # Syllabus
    url(r'^teacher/course/(\d+)/syllabus$', syllabus.syllabus_page),
    url(r'^teacher/course/(\d+)/syllabus_modal$', syllabus.syllabus_modal),
    url(r'^teacher/course/(\d+)/save_syllabus$', syllabus.save_syllabus),
    url(r'^teacher/course/(\d+)/delete_syllabus$', syllabus.delete_syllabus),

    # Policy
    url(r'^teacher/course/(\d+)/policy$', policy.policy_page),
    url(r'^teacher/course/(\d+)/policy_modal$', policy.policy_modal),
    url(r'^teacher/course/(\d+)/save_policy$', policy.save_policy),
    url(r'^teacher/course/(\d+)/delete_policy$', policy.delete_policy),

    # Lecture
    url(r'^teacher/course/(\d+)/lectures$', lecture.lectures_page),
    url(r'^teacher/course/(\d+)/lectures_table$', lecture.lectures_table),
    url(r'^teacher/course/(\d+)/lecture_modal$', lecture.lecture_modal),
    url(r'^teacher/course/(\d+)/save_lecture$', lecture.save_lecture),
    url(r'^teacher/course/(\d+)/delete_lecture$', lecture.delete_lecture),

    # Lecture Note(s)
    url(r'^teacher/course/(\d+)/lecture/(\d+)/notes$', lecture_note.lecture_notes_page),
    url(r'^teacher/course/(\d+)/lecture/(\d+)/lecture_notes_table$', lecture_note.lecture_notes_table),
    url(r'^teacher/course/(\d+)/lecture/(\d+)/lecture_note_modal$', lecture_note.lecture_note_modal),
    url(r'^teacher/course/(\d+)/lecture/(\d+)/save_lecture_note$', lecture_note.save_lecture_note),
    url(r'^teacher/course/(\d+)/lecture/(\d+)/delete_lecture_note$', lecture_note.delete_lecture_note),
                       
    # Assignment(s)
    url(r'^teacher/course/(\d+)/assignments$', assignment.assignments_page),
    url(r'^teacher/course/(\d+)/assignments_table$', assignment.assignments_table),
    url(r'^teacher/course/(\d+)/assignment_modal$', assignment.assignment_modal),
    url(r'^teacher/course/(\d+)/save_assignment$', assignment.save_assignment),
    url(r'^teacher/course/(\d+)/delete_assignment$', assignment.delete_assignment),

    # Assignment
    url(r'^teacher/course/(\d+)/assignment/(\d+)$', assignment.assignment_page),
    url(r'^teacher/course/(\d+)/assignment/(\d+)/questions_table$', assignment.questions_table),
    url(r'^teacher/course/(\d+)/assignment/(\d+)/question_type_modal$', assignment.question_type_modal),
    url(r'^teacher/course/(\d+)/assignment/(\d+)/question_essay_modal$', assignment.question_essay_modal),
    url(r'^teacher/course/(\d+)/assignment/(\d+)/question_multiple_choice_modal$', assignment.question_multiple_choice_modal),
    url(r'^teacher/course/(\d+)/assignment/(\d+)/question_true_false_modal$', assignment.question_true_false_modal),
    url(r'^teacher/course/(\d+)/assignment/(\d+)/question_response_modal$', assignment.question_response_modal),
    url(r'^teacher/course/(\d+)/assignment/(\d+)/save_question$', assignment.save_question),
    url(r'^teacher/course/(\d+)/assignment/(\d+)/delete_question$', assignment.delete_question),

    # Quiz(es)
    url(r'^teacher/course/(\d+)/quizzes$', quiz.quizzes_page),
    url(r'^teacher/course/(\d+)/quizzes_table$', quiz.quizzes_table),
    url(r'^teacher/course/(\d+)/quiz_modal$', quiz.quiz_modal),
    url(r'^teacher/course/(\d+)/save_quiz$', quiz.save_quiz),
    url(r'^teacher/course/(\d+)/delete_quiz$', quiz.delete_quiz),

    # Quiz
    url(r'^teacher/course/(\d+)/quiz/(\d+)$', quiz.quiz_page),
    url(r'^teacher/course/(\d+)/quiz/(\d+)/questions_table$', quiz.questions_table),
    url(r'^teacher/course/(\d+)/quiz/(\d+)/question_type_modal$', quiz.question_type_modal),
    url(r'^teacher/course/(\d+)/quiz/(\d+)/question_true_false_modal$', quiz.question_true_false_modal),
    url(r'^teacher/course/(\d+)/quiz/(\d+)/save_question$', quiz.save_question),
    url(r'^teacher/course/(\d+)/quiz/(\d+)/delete_question$', quiz.delete_question),

    # Exam(s)
    url(r'^teacher/course/(\d+)/exams$', exam.exams_page),
    url(r'^teacher/course/(\d+)/exams_table$', exam.exams_table),
    url(r'^teacher/course/(\d+)/exam_modal$', exam.exam_modal),
    url(r'^teacher/course/(\d+)/save_exam$', exam.save_exam),
    url(r'^teacher/course/(\d+)/delete_exam$', exam.delete_exam),
    
    # # Exam
    url(r'^teacher/course/(\d+)/exam/(\d+)$', exam.exam_page),
    url(r'^teacher/course/(\d+)/exam/(\d+)/questions_table$', exam.questions_table),
    url(r'^teacher/course/(\d+)/exam/(\d+)/question_type_modal$', exam.question_type_modal),
    url(r'^teacher/course/(\d+)/exam/(\d+)/question_multiple_choice_modal$', exam.question_multiple_choice_modal),
    url(r'^teacher/course/(\d+)/exam/(\d+)/save_question$', exam.save_question),
    url(r'^teacher/course/(\d+)/exam/(\d+)/delete_question$', exam.delete_question),
                       
    # Discussion
    url(r'^teacher/course/(\d+)/discussion$', discussion.discussion_page),
    url(r'^teacher/course/(\d+)/discussions_table$', discussion.discussions_table),
    url(r'^teacher/course/(\d+)/new_thread$', discussion.new_thread_modal),
    url(r'^teacher/course/(\d+)/insert_thread$', discussion.insert_thread),
    url(r'^teacher/course/(\d+)/delete_thread$', discussion.delete_thread),
    url(r'^teacher/course/(\d+)/thread/(\d+)$', discussion.posts_page),
    url(r'^teacher/course/(\d+)/thread/(\d+)/posts_table$', discussion.posts_table),
    url(r'^teacher/course/(\d+)/thread/(\d+)/new_post$', discussion.new_post_modal),
    url(r'^teacher/course/(\d+)/thread/(\d+)/insert_post$', discussion.insert_post),
                       
    # Peer-Review
    url(r'^teacher/course/(\d+)/peer_reviews$', peer_review.peer_reviews_page),
    url(r'^teacher/course/(\d+)/peer_review/(\d+)$', peer_review.assignment_page),
    url(r'^teacher/course/(\d+)/peer_review/(\d+)/peer_review_modal$', peer_review.peer_review_modal),
    url(r'^teacher/course/(\d+)/peer_review/(\d+)/save_peer_review$', peer_review.save_peer_review),
    url(r'^teacher/course/(\d+)/peer_review/(\d+)/delete_peer_review$', peer_review.delete_peer_review),
    url(r'^teacher/course/(\d+)/peer_review/(\d+)/update_assignment_marks$', peer_review.update_assignment_marks),
                       
    # Settings
    url(r'^teacher/course/(\d+)/settings$', setting.settings_page),
    url(r'^teacher/course/(\d+)/suspend_course$', setting.suspend_course),

]

onlineportal/core/models.py
from django.db import models
from classroom.models import Course

# Create your models here.
class About(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField()
    image = models.ImageField(upload_to='pictures')
    name = models.CharField(max_length=300)
    satisfied_students = models.IntegerField()
    courses_offered = models.IntegerField()
    expert_advisors = models.IntegerField()
    schools = models.IntegerField()

class StudentsMessages(models.Model):
    image=models.ImageField(upload_to='student_messages')
    description=models.TextField()
    student_name =models.CharField(max_length=200)
    coursename =models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return self.coursename.title 

onlineportal/teachers/models.py
from django.db import models

# Create your models here.

onlineportal/classroom/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.utils import ValidationError
from classroom.models import (Answer, Question, Student, StudentAnswer,
                              Subject, User, Profile)


from datetime import date
from django.db import models
from django.forms import ModelForm, Textarea, TextInput, NumberInput
from django.forms import Select, SelectDateWidget
from django.forms.widgets import EmailInput
from django.conf import settings
from django.core.exceptions import ValidationError
from captcha.fields import CaptchaField
from .models import LandpageContactMessage


class TeacherSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_teacher = True
        if commit:
            user.save()
        return user


class StudentSignUpForm(UserCreationForm):
    interests = forms.ModelMultipleChoiceField(
        queryset=Subject.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.save()
        student = Student.objects.create(user=user)
        student.interests.add(*self.cleaned_data.get('interests'))
        return user


class StudentInterestsForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('interests', )
        widgets = {
            'interests': forms.CheckboxSelectMultiple
        }


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('text', 'sub_subjects')


class BaseAnswerInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        super().clean()

        has_one_correct_answer = False
        for form in self.forms:
            if not form.cleaned_data.get('DELETE', False):
                if form.cleaned_data.get('is_correct', False):
                    has_one_correct_answer = True
                    break
        if not has_one_correct_answer:
            raise ValidationError('Mark at least one answer as correct.', code='no_correct_answer')


class TakeQuizForm(forms.ModelForm):
    answer = forms.ModelChoiceField(
        queryset=Answer.objects.none(),
        widget=forms.RadioSelect(),
        required=True,
        empty_label=None)

    class Meta:
        model = StudentAnswer
        fields = ('answer', )

    def __init__(self, *args, **kwargs):
        question = kwargs.pop('question')
        super().__init__(*args, **kwargs)
        self.fields['answer'].queryset = question.answers.order_by('text')

class ContactForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = LandpageContactMessage
        fields = ['name','email', 'phone', 'message']
        labels = {
        }
        widgets = {
            'name': TextInput(attrs={'class': u'form-control','placeholder': u'Enter Full Name'}),
            'email': EmailInput(attrs={'class': u'form-control','placeholder': u'Enter Email'}),
            'phone': TextInput(attrs={'class': u'form-control','placeholder': u'Enter Phone'}),
            'comment': Textarea(attrs={'class': u'form-control','placeholder': u'Enter Comment'}),
    }
    

    def clean_phone(self):
        phone = self.cleaned_data.get('phone', None)
        
        # clean phone by removing all non-numerals
        phone = ''.join(x for x in phone if x.isdigit())
        
        ph_length = str(phone)
        min_length = 10
        max_length = 13
        if len(ph_length) < min_length:
            raise ValidationError('Must be 10 digit phone number.')
        if len(ph_length) > max_length:
            raise ValidationError('Must be at maxium 13 digits long')
        return phone


class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(
        label='Email',
        max_length=100,
        widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Email'}),
    )
    captcha = CaptchaField()

class UserUpdateForm(forms.ModelForm):
    email=forms.EmailField()
    class Meta:
        model=User
        fields=['username','email']
    
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']   

onlineportal/teachers/views/policy.py
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from classroom.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.conf import settings
import json
import datetime
from classroom.models import Teacher
from classroom.models import Course
from registrar.models import Policy
from teachers.forms import PolicyForm

@login_required(login_url=settings.LOGIN_URL)
def policy_page(request, course_id):
    course = Course.objects.get(id=course_id)
    try:
        policy = Policy.objects.get(course=course)
    except Policy.DoesNotExist:
        policy = None
    return render(request, 'teacher/policy/view.html',{
        'course' : course,
        'policy' : policy,
        'user' : request.user,
        'tab' : 'policy',
        'HAS_ADVERTISMENT': settings.APPLICATION_HAS_ADVERTISMENT,
        'local_css_urls' : settings.SB_ADMIN_2_CSS_LIBRARY_URLS,
        'local_js_urls' : settings.SB_ADMIN_2_JS_LIBRARY_URLS,
    })

@login_required(login_url=settings.LOGIN_URL)
def policy_modal(request, course_id):
    if request.method == u'POST':
        form = PolicyForm()
        return render(request, 'teacher/policy/modal.html',{'form' : form })


@login_required(login_url=settings.LOGIN_URL)
def save_policy(request, course_id):
    response_data = {'status' : 'failed', 'message' : 'unknown error with saving'}
    if request.is_ajax():
        if request.method == 'POST':
            form = PolicyForm(request.POST, request.FILES)
            if form.is_valid():
                course = Course.objects.get(id=course_id)
                form.instance.course = course
                form.save()
                response_data = {'status' : 'success', 'message' : 'saved'}
            else:
                response_data = {'status' : 'failed', 'message' : json.dumps(form.errors)}
    return HttpResponse(json.dumps(response_data), content_type="application/json")


@login_required(login_url=settings.LOGIN_URL)
def delete_policy(request, course_id):
    response_data = {'status' : 'failed', 'message' : 'unknown error with deleting'}
    if request.is_ajax():
        if request.method == 'POST':
            policy_id = int(request.POST['policy_id'])
            teacher = Teacher.objects.get(user=request.user)
            try:
                policy = Policy.objects.get(policy_id=policy_id)
                if policy.course.teacher == teacher:
                    policy.delete()
                    response_data = {'status' : 'success', 'message' : 'deleted'}
                else:
                    response_data = {'status' : 'failed', 'message' : 'unauthorized deletion'}
            except Policy.DoesNotExist:
                response_data = {'status' : 'failed', 'message' : 'record does not exist'}
    return HttpResponse(json.dumps(response_data), content_type="application/json")

onlineportal/teachers/templates/teacher/quiz/form.html
<form>
    <input type="hidden"
             id="id_quiz_id"
           name="quiz_id"
          value={% if form.instance.quiz_id != None %}"{{ form.instance.quiz_id }}"{% else %}0{% endif %}>
    {% if form.instance.question_type != None %}
    <input type="hidden"
             id="id_question_type"
           name="question_type"
          value="{{ form.instance.question_type }}">
    {% endif %}
    {% for field in form %}
    <div class="row">
        <div class="form-group">
            <div class="fieldWrapper">
                <label class="col-sm-3 control-label">
                    {{ field.label }}
                </label>
                <div class="col-sm-9">
                    {{ field }}
                </div>
            </div>
        </div>
    </div>
    <br/>
    {% endfor %}
</form>

onlineportal/teachers/templates/teacher/quiz/question_modal.html
<div class="modal fade" id="question_modal" role="dialog">
    <div class="modal-dialog" style="width:50%;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h2 class="modal-title" id="myModalLabel">{{ title }}</h2>
            </div>
            <div class="modal-body">
                {% include "teacher/quiz/form.html" with form=form %}
                
                <!-- Error Message Box -->
                <div id="error_box" name="error_box" class="alert alert-danger alert-dismissable" hidden="true">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    ERROR: This is to be filled in by the "print_error" function. If you see this message that means there's an error with your javascript somewhere.
                </div><!-- /.Error Message Box -->
            </div>
            <div class="modal-footer">
                <button type="button"
                       class="btn btn-primary"
                     onclick="ajax_save_question({{ form.instance.question_id }});">
                    <i class="fa fa-check-circle"></i> Submit
                </button>
            </div>
        </div>
    </div>
</div>
<script>
    /**
     * Dynamic UI Code.
     *  To give our application a dynamic feel, the following jQuery code will be
     *  used to perform various UI changes.
     */
     $(document).ready(function(){
        $('#question_modal').on('hidden.bs.modal', function (e) {
            $('#question_modal').html('');
             $('#add_question_btn').prop("disabled", false);
             $('#edit_{{ form.instance.question_id }}_{{ form.instance.question_type }}_btn').prop("disabled", false); 
        });
    });

    function ajax_save_question(question_id)
    {
        // If no question_id was entered then set it to zero to tell our
        // controller that we are inserting a new question.
        if (typeof(question_id)==='undefined')
        {
            question_id = 0;
        }

        // Create a FormData Object using your form dom element and load
        // up the initial data first, then update it on question type.

        // Basic
        var data = new FormData();
        data.append('csrfmiddlewaretoken', '{{ csrf_token }}');
        data.append('question_type', $('#id_question_type').val());
        data.append('question_num', $('#id_question_num').val());
        data.append('question_id', question_id);
        data.append('title', $('#id_title').val());
        data.append('description', $('#id_description').val());
        data.append('marks', $('#id_marks').val());

        // True/False Choice
        data.append('true_choice', $('#id_true_choice').val());
        data.append('false_choice', $('#id_false_choice').val());
        data.append('answer', $('#id_answer').is(':checked'));

        jQuery.ajax({
            url: {{ quiz.quiz_id }} + '/save_question',
            data: data,
            cache: false,
            contentType: false,
            processData: false,
            type: 'POST',
            success: function(json_result){
                // success code execution here
                if (json_result.status == "success")
                {
                    $('#question_modal').modal('hide');
                    ajax_refresh_questions_table();
                }
                else
                {
                    print_error(json_result.message);
                }
            },
            error: function(xhr,status,error) {
                // error code here
            },
            complete: function(xhr,status) {
               // completion code here
            }
        });

    }

/**
 * Prints a error box with the contents of the errors received from the server.
 */
function print_error(json_result)
{
    $('#error_box').prop("hidden", false); // Display error box.
    
    // Iterate through the JSON array of arrays and generate an error string.
    var message = "<b>Error(s):</b><hr/>";
    var data = $.parseJSON(json_result)
    for (var key in data) {
        if (data.hasOwnProperty(key)) { // this will check if key is owned by data object and not by any of it's ancestors
            message += "<p>" + key + ": " + data[key] + "<p>";
        }
    }
    
    // Replace the error string with the contents of the error box.
    $('#error_box').html(message);
}

</script>

onlineportal/teachers/templates/teacher/quiz/question_table.html
<div class="row">
    <div class="col-lg-12 text-center">
        <div class="panel panel-default">
            <div class="panel-body">
                <h2 align="left" valign="left">Questions</h2>
                <div class="table-responsive">
                    <table class="table table-hover table-striped">
                        <thead>
                            <tr>
                                <th>Question #</th>
                                <th>Type</th>
                                <th>
                                    <button onclick="ajax_question(0,0);"
                                                 id="add_question_btn"
                                               name="add_question_btn"
                                               type="button"
                                              class="btn btn-sm btn-success">
                                        <i class="fa fa-plus"></i> Question
                                    </button>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for tf_question in tf_questions %}
                            <tr>
                                <td align="left" valign="left">{{ tf_question.question_num }}</td>
                                <td align="left" valign="left">True/False</td>
                                <td align="left" valign="left">
                                    <button onclick="ajax_question({{ tf_question.question_id }},{{ TRUEFALSE_QUESTION_TYPE }});"
                                                 id="edit_{{ tf_question.question_id }}_{{ TRUEFALSE_QUESTION_TYPE }}_btn"
                                               name="edit_{{ tf_question.question_id }}_{{ TRUEFALSE_QUESTION_TYPE }}_btn"
                                               type="button"
                                              class="btn btn-sm btn-warning">
                                            <i class="fa fa-pencil"></i> Edit
                                    </button>
                                    <button onclick="ajax_delete_question({{ tf_question.question_id }},{{ TRUEFALSE_QUESTION_TYPE }});"
                                                 id="del_{{ tf_question.question_id }}_{{ TRUEFALSE_QUESTION_TYPE }}_btn"
                                               name="del_{{ tf_question.question_id }}_{{ TRUEFALSE_QUESTION_TYPE }}_btn"
                                               type="button"
                                              class="btn btn-sm btn-danger">
                                        <i class="fa fa-minus"></i> Delete
                                    </button>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

onlineportal/teachers/templates/teacher/quiz/quiz_modal.html
<div class="modal fade" id="quiz_modal" role="dialog">
    <div class="modal-dialog" style="width:50%;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h2 class="modal-title" id="myModalLabel">New Quiz</h2>
            </div>
            <div class="modal-body">
                {% include "teacher/quiz/form.html" with form=form %}
                
                <!-- Error Message Box -->
                <div id="error_box" name="error_box" class="alert alert-danger alert-dismissable" hidden="true">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    ERROR: This is to be filled in by the "print_error" function. If you see this message that means there's an error with your javascript somewhere.
                </div><!-- /.Error Message Box -->
            </div>
            <div class="modal-footer">
                <button onclick="ajax_save_quiz();"
                             id="save_quiz_btn"
                           name="save_quiz_btn"
                           type="button"
                          class="btn btn-primary">
                    <i class="fa fa-check-circle"></i> Submit
                </button>
            </div>
        </div>
    </div>
</div>
<script>
    /**
     * Dynamic UI Code.
     *  To give our application a dynamic feel, the following jQuery code will be
     *  used to perform various UI changes.
     */
     $(document).ready(function(){
        $('#quiz_modal').on('hidden.bs.modal', function (e) {
            $('#quiz_modal').html('');
            $('#add_quiz_btn').prop("disabled", false);
            $('#edit_{{ form.instance.quiz_id }}_btn').prop("disabled", false);
        });
    });
    
    function ajax_save_quiz()
    {
        $('#save_quiz_btn').prop("disabled", true);
        
        // create a FormData Object using your form dom element
        var data = new FormData();
        data.append('csrfmiddlewaretoken', '{{ csrf_token }}');
        data.append('quiz_id', $('#id_quiz_id').val());
        data.append('title', $('#id_title').val());
        data.append('description', $('#id_description').val());
        data.append('quiz_num', $('#id_quiz_num').val());
        var date = '';
        date  = $('#id_start_date_year').val() + '-';
        date += $('#id_start_date_month').val() + '-';
        date += $('#id_start_date_day').val();
        data.append('start_date', date);
        date  = $('#id_due_date_year').val() + '-';
        date += $('#id_due_date_month').val() + '-';
        date += $('#id_due_date_day').val();
        data.append('due_date', date);
        data.append('worth', $('#id_worth').val());
        
        jQuery.ajax({
            url: 'save_quiz',
            data: data,
            cache: false,
            contentType: false,
            processData: false,
            type: 'POST',
            success: function(json_result){
                // success code execution here
                if (json_result.status == "success")
                {
                    $('#quiz_modal').modal('hide');
                    ajax_refresh_quizzes_table();
                }
                else
                {
                    print_error(json_result.message);
                }
            },
            error: function(xhr,status,error) {
                // error code here
            },
            complete: function(xhr,status) {
               // completion code here
               $('#save_quiz_btn').prop("disabled", false);
            }
        });

    }

    /**
     * Prints a error box with the contents of the errors received from the server.
     */
    function print_error(json_result)
    {
        $('#error_box').prop("hidden", false); // Display error box.
    
        // Iterate through the JSON array of arrays and generate an error string.
        var message = "<b>Error(s):</b><hr/>";
        var data = $.parseJSON(json_result)
        for (var key in data) {
            if (data.hasOwnProperty(key)) { // this will check if key is owned by data object and not by any of it's ancestors
                message += "<p>" + key + ": " + data[key] + "<p>";
            }
        }
    
        // Replace the error string with the contents of the error box.
        $('#error_box').html(message);
    }
</script>